Repository LumiSpy/lumispy, pull requests merged in 2022-04, with the labels that each got.

#117 Add python 3.10
  .github/workflows/release.yml
  .github/workflows/tests.yml
  CHANGELOG.rst
  setup.py
Labels: status: needs review

#120 HyperSpy v1.7 adaptions
  CHANGELOG.rst
  doc/source/index.rst
  doc/source/user_guide/installation.rst
  doc/source/user_guide/introduction.rst
  doc/source/user_guide/signal_axis.rst
  lumispy/signals/cl_spectrum.py
  lumispy/signals/luminescence_spectrum.py
  lumispy/tests/utils/test_axis-conversion.py
  lumispy/tests/utils/test_joinspectra.py
  lumispy/utils/axes.py
  setup.py
Labels: status: needs review

#118 reorganize transient classes
  CHANGELOG.rst
  doc/source/user_guide/introduction.rst
  lumispy/hyperspy_extension.yaml
  lumispy/signals/__init__.py
  lumispy/signals/common_transient.py
  lumispy/signals/luminescence_transient.py
  lumispy/signals/luminescence_transientspec.py
  lumispy/tests/signals/test_common_luminescence.py
  lumispy/tests/test_signal_registration.py
Labels: status: needs review

#122 Add documentation of utility functions
  doc/source/index.rst
  doc/source/user_guide/utilities.rst
Labels: status: WIP

#116 Update metadata used in scale_by_exposure
  CHANGELOG.rst
  CONTRIBUTING.rst
  lumispy/signals/common_luminescence.py
  lumispy/tests/signals/test_common_luminescence.py
Labels: status: needs review

#114 Fixing deprecation warning
  lumispy/signals/luminescence_spectrum.py
  lumispy/tests/signals/test_luminescence_spectrum.py
Labels: status: waiting for author
